---
title: "Respirometry data analysis C. Fleming Last updated: 12/8/22"
output:
  pdf_document: default
  html_notebook: default
authors: Caroline Fleming

#Some resources:
  #https://rstudio-pubs-static.s3.amazonaws.com/63556_e35cc7e2dfb54a5bb551f3fa4b3ec4ae.html

---

```{r Setting up all packages}
require("knitr")
#install.packages("lme4")
#compare with and without predictor
#library(lme4)
#install.packages("lmerTest")
library("lmerTest")
#install.packages("Matrix")
library("Matrix")
#install.packages("lme4")
library("lme4")
#install.packages("emmeans")
library("emmeans")
#install.packages("pbkrtest")
library("pbkrtest")
library("tidyverse")
library("performance")
#install.packages("see")
library("see")
#install.packages("ggrepel")
library("ggrepel")
#install.packages("sjPlot") #for visualizing linear models
library(sjPlot)

```


```{r Set working directory and upload data}
opts_knit$set(root.dir = "C:/Users/carol/Documents/PhD Boston University 2019-/Chapter_2_Ecotox/Summer_2022_N_Ecotox")
getwd()
resp_all.data <- read.csv("RESP_ALL_SUMMARY_cleaned_12_14_22.csv", header=TRUE, sep=",",stringsAsFactors = FALSE)

hist(resp_all.data$resp_rate)
qqnorm(resp_all.data$resp_rate)

#make sure treatID is a character
resp_all.data$treat_ID_full<-as.character(resp_all.data$treat_ID_full)

#adding a log transformed resp rate
resp_all.data$log_resp_rate<-abs(resp_all.data$resp_rate)
resp_all.data$log_resp_rate<-log(resp_all.data$log_resp_rate)
resp_all.data$arcsin_resp_rate<-asin(resp_all.data$resp_rate)

#testing for normality
#TESTING FOR NORMALITY IN PAM_delta
#install new package to see what the best transformation is
#install.packages("bestNormalize")
library("bestNormalize")
bestNormalize(resp_all.data$resp_rate)
#in order for this to work I need to change the PAM_delta in to a vector
resp_all.data$resp_rate_vector<-as.vector(resp_all.data$resp_rate_vector)
#then I run the orderNorm command into a new object
orderNormobj_resp_rate<-orderNorm(resp_all.data$resp_rate)
#this object gives us what we want, but we have to index from that object and put it in a new column
resp_all.data$ordernorm_resp_rate<-orderNormobj_resp_rate$x.t
```



```{r linear models - ALL DATA}
mm_resp_null <- lmer(resp_rate ~ 1 + (1|vial_ID), data= resp_all.data)
summary(mm_resp_null)
#that null looks good

mm_resp_1 <- lmer(resp_rate ~ N_species + N_dose + temp + food + sym_state + e_coli_plate + (1|vial_ID), data= resp_all.data)
summary(mm_resp_1)
# the factors that are not significant and I will drop: Nspecies, food

mm_resp_2 <- lmer(resp_rate ~ N_dose + + N_species + temp + sym_state + e_coli_plate + (1|vial_ID), data= resp_all.data)
summary(mm_resp_2)
emm_resp_2=emmeans(mm_resp_2, specs=pairwise ~ N_species)
summary(emm_resp_2)
#go with this one

#checking out where the changes are
all_20C<-subset(resp_all.data, resp_all.data$temp==20)
all_30C<-subset(resp_all.data, resp_all.data$temp==30)
all_apo<-subset(resp_all.data, resp_all.data$sym_state=="A")
all_sym<-subset(resp_all.data, resp_all.data$sym_state=="S")
all_e_coli<-subset(resp_all.data, resp_all.data$e_coli_plate=="1")
all_no_e_coli<-subset(resp_all.data, resp_all.data$e_coli_plate=="0")

mean(all_20C$resp_rate, na.rm=TRUE)
# -0.004676263
mean(all_30C$resp_rate, na.rm=TRUE)
# -0.004191459
mean(all_apo$resp_rate, na.rm=TRUE)
# -0.004231038
mean(all_sym$resp_rate, na.rm=TRUE)
# -0.004632639
mean(all_e_coli$resp_rate, na.rm=TRUE)
# -0.004617116
mean(all_no_e_coli$resp_rate, na.rm=TRUE)
# -0.004230682

mm_resp_3 <- lmer(resp_rate ~ N_dose  + temp + sym_state + e_coli_plate + N_dose*temp + N_dose*sym_state + sym_state*temp + (1|vial_ID), data= resp_all.data)
summary(mm_resp_3)

mm_resp_4 <- lmer(resp_rate ~ N_dose  + temp + sym_state + e_coli_plate +  N_dose*sym_state + sym_state*temp + (1|vial_ID), data= resp_all.data)
summary(mm_resp_4)

mm_resp_5 <- lmer(resp_rate ~ N_dose  + temp + sym_state + e_coli_plate + sym_state*temp + (1|vial_ID), data= resp_all.data)
summary(mm_resp_5)

mm_resp_6 <- lmer(resp_rate ~ N_dose  + temp + sym_state + e_coli_plate +  N_dose*sym_state + (1|vial_ID), data= resp_all.data)
summary(mm_resp_6)

#AIC 
AIC_table_pam<-AIC(mm_resp_1, mm_resp_2, mm_resp_3, mm_resp_4, mm_resp_5, mm_resp_6)
AIC_table_pam

#lower AIC wins, mm_resp_2 wins
```
```{r linear models - E. COLI DATA}

#make dose a factor
e_coli$N_dose<-as.factor(e_coli$N_dose)
mm_resp_e_coli_null <- lmer(resp_rate ~ 1 + (1|vial_ID), data= e_coli)
summary(mm_resp_e_coli_null)
#that null looks good

mm_resp_e_coli_1 <- lmer(resp_rate ~ N_species + N_dose + temp + food + sym_state + e_coli_plate + (1|vial_ID), data= e_coli)
summary(mm_resp_e_coli_1)
# the factors that are not significant and I will drop: Nspecies, food

mm_resp_e_coli_2 <- lmer(resp_rate ~ N_dose  + temp + sym_state + (1|vial_ID), data= e_coli)
summary(mm_resp_e_coli_2)
emm_resp_e_coli_2=emmeans(mm_resp_e_coli_2, specs=pairwise ~sym_state)
summary(emm_resp_e_coli_2)
#go with this one

mean(e_coli[e_coli$sym_state == "A","resp_rate"], na.rm=TRUE) #calculates the mean of resp_rate in the sym_state column where values are A
#-0.004370495

mean(e_coli[e_coli$sym_state == "S","resp_rate"], na.rm=TRUE) #calculates the mean of resp_rate in the sym_state column where values are A
#-0.004912


mean(e_coli[e_coli$temp == "20","resp_rate"], na.rm=TRUE) #calculates the mean of resp_rate in the sym_state column where values are A
#-0.004933947

mean(e_coli[e_coli$temp == "30","resp_rate"], na.rm=TRUE) #calculates the mean of resp_rate in the sym_state column where values are A
#-0.004343118

mean(e_coli[e_coli$N_dose == "0","resp_rate"], na.rm=TRUE) #calculates the mean of resp_rate in the sym_state column where values are A
#-0.004231979

mean(e_coli[e_coli$N_dose == "10","resp_rate"], na.rm=TRUE) #calculates the mean of resp_rate in the sym_state column where values are A
#-0.005326042

mean(e_coli[e_coli$N_dose == "18","resp_rate"], na.rm=TRUE) #calculates the mean of resp_rate in the sym_state column where values are A
#-0.005102128

```

```{r linear models - NO E. COLI DATA}

#make dose a factor
no_e_coli$N_dose<-as.factor(no_e_coli$N_dose)
mm_resp_no_e_coli_null <- lmer(resp_rate ~ 1 + (1|vial_ID), data= no_e_coli)
summary(mm_resp_no_e_coli_null)
#that null looks good

mm_resp_no_e_coli_1 <- lmer(resp_rate ~ N_species + N_dose + temp + food + sym_state  + (1|vial_ID), data= no_e_coli)
summary(mm_resp_no_e_coli_1)
# the factors that are not significant and I will drop: Nspecies, food

mm_resp_no_e_coli_2 <- lmer(resp_rate ~ N_dose  + temp + sym_state + (1|vial_ID), data= no_e_coli)
summary(mm_resp_no_e_coli_2)
emm_resp_no_e_coli_2=emmeans(mm_resp_no_e_coli_2, specs=pairwise ~ temp, na.rm=TRUE)
summary(emm_resp_no_e_coli_2)
#go with this one

```
```

```


```{r linear model fitness }
#posthoc pairwise
#need to change the max print because we have so many comparisons
options(max.print = 10000)   
emm_treat_ID=emmeans(mm_resp_2, specs=pairwise ~ N_species)
summary(emm_treat_ID)

#checking for model fit
plot(mm_resp_2) #homogeneity of variance,looks okay
r2(mm_resp_2) #marginal id variance just by fixed factors, conditional includes variance explained by random factor
  # treatment explains 9.5% of variation in ln.sum.arms
?check_model()

check_collinearity(mm_resp_2) #check for predictor variables are correlated
#check_model(mm_resp_treat)
check_outliers(mm_resp_2)
check_heteroscedasticity(mm_resp_2)
check_homogeneity(mm_resp_2) #plot
check_autocorrelation(mm_resp_2) #plot

plot(mm_resp_2)
```






```{r all subsets}
control_all_20<-subset(resp_all.data, resp_all.data$N_dose=="0" & resp_all.data$temp=="20")
control_ecoli_20<-subset(resp_all.data, resp_all.data$N_dose=="0" & resp_all.data$temp=="20" & resp_all.data$e_coli=="1")
control_no_ecoli_20<-subset(resp_all.data, resp_all.data$N_dose=="0" & resp_all.data$temp=="20" & resp_all.data$e_coli=="0")
control_all_30<-subset(resp_all.data, resp_all.data$N_dose=="0" & resp_all.data$temp=="30")
control_ecoli_30<-subset(resp_all.data, resp_all.data$N_dose=="0" & resp_all.data$temp=="30" & resp_all.data$e_coli=="1")
control_no_ecoli_30<-subset(resp_all.data, resp_all.data$N_dose=="0" & resp_all.data$temp=="30" & resp_all.data$e_coli=="0")
A_5_20 <-subset(resp_all.data, resp_all.data$N_species=="A"& resp_all.data$N_dose=="5" & resp_all.data$temp=="20")
A_5_30 <- A_5_20 <-subset(resp_all.data, resp_all.data$N_species=="A"& resp_all.data$N_dose=="5" & resp_all.data$temp=="30")
A_7.5_20 <-subset(resp_all.data, resp_all.data$N_species=="A"& resp_all.data$N_dose=="7.5" & resp_all.data$temp=="20")
A_7.5_30 <- A_5_20 <-subset(resp_all.data, resp_all.data$N_species=="A"& resp_all.data$N_dose=="7.5" & resp_all.data$temp=="30")
A_10_20 <-subset(resp_all.data, resp_all.data$N_species=="A"& resp_all.data$N_dose=="10" & resp_all.data$temp=="20")
A_10_30 <- A_5_20 <-subset(resp_all.data, resp_all.data$N_species=="A"& resp_all.data$N_dose=="10" & resp_all.data$temp=="30")
N_1.5_20 <-subset(resp_all.data, resp_all.data$N_species=="N"& resp_all.data$N_dose=="1.5" & resp_all.data$temp=="20")
N_1.5_30 <- A_5_20 <-subset(resp_all.data, resp_all.data$N_species=="N"& resp_all.data$N_dose=="1.5" & resp_all.data$temp=="30")
N_5_20 <-subset(resp_all.data, resp_all.data$N_species=="N"& resp_all.data$N_dose=="5" & resp_all.data$temp=="20")
N_5_30 <- A_5_20 <-subset(resp_all.data, resp_all.data$N_species=="N"& resp_all.data$N_dose=="5" & resp_all.data$temp=="30")
N_18_20 <-subset(resp_all.data, resp_all.data$N_dose=="18" & resp_all.data$temp=="20")
N_18_30 <-subset(resp_all.data, resp_all.data$N_dose=="18" & resp_all.data$temp=="30")
e_coli<-subset(resp_all.data, resp_all.data$e_coli==1)
no_e_coli<-subset(resp_all.data, resp_all.data$e_coli==0)
N_18_30_e_coli <-subset(resp_all.data, resp_all.data$N_dose=="18" & resp_all.data$temp=="30" & resp_all.data$e_coli==1)

#e coli controls
t.test(control_ecoli_30$resp_rate, control_no_ecoli_30$resp_rate)


#means of e coli vs no e coli
mean(e_coli$resp_rate)
#-0.00445
mean(no_e_coli$resp_rate)
#-0.003760578

# Control 20 v control 30
t.test(control_all_20$resp_rate, control_all_30$resp_rate)
# A 5 20 v A 5 30
t.test(A_5_20$resp_rate, A_5_30$resp_rate)
# A 7.5 20 v A 7.5 30
t.test(A_7.5_20$resp_rate, A_7.5_30$resp_rate)
# Control 20 v. A10 20
t.test(control_all_20$resp_rate, A_10_20$resp_rate)
# Control 30 v. A10 30
t.test(control_all_30$resp_rate, A_10_30$resp_rate)
# A10 20 v A10 30
t.test(A_10_20$resp_rate, A_10_30$resp_rate)
# N 1.5 20 v N 1.5 30
t.test(N_1.5_20$resp_rate, N_1.5_30$resp_rate)
# N 5 20 v N 5 30
t.test(N_5_20$resp_rate, N_5_30$resp_rate)
# Control 20 v. N18 20
t.test(control_all_20$resp_rate, N_18_20$resp_rate)
# Control 30 v. Control N18 30
t.test(control_all_30$resp_rate, N_18_30$resp_rate)

# e coli vs. no ecoli 
t.test(e_coli$resp_rate, no_e_coli$resp_rate)
# N 18 e coli 30 vs. control 30
t.test(control_all_30$resp_rate, N_18_30_e_coli$resp_rate)
       
```


```{r Graphs}
#1
gg_resp_all_ecoli<-
  ggplot(e_coli, aes(x=treat_ID_full, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - E. coli")
gg_resp_all_ecoli

#2
gg_food_sym_state_ecoli<-
  ggplot(e_coli, aes(x=food_sym_state, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Food and Symbiotic State (Food_Symstate) - E. coli")
gg_food_sym_state_ecoli

#3
gg_resp_all_no_ecoli<-
  ggplot(no_e_coli, aes(x=treat_ID_collapsed_controls, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by treat ID - No E. coli")
gg_resp_all_no_ecoli

#4
gg_food_sym_state_no_ecoli<-
  ggplot(no_e_coli, aes(x=food_sym_state, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Food and Symbiotic State (Food_Symstate) - No E. coli")
gg_food_sym_state_no_ecoli


#5
gg_N_species_dose_ecoli<-
  ggplot(e_coli, aes(x=N_species_dose, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
  geom_label(position="jitter", label=col_num)+
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual()+
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by N_species_dose - E. coli")
gg_N_species_dose_ecoli
?geom_label

#6
gg_N_species_dose_no_ecoli<-
  ggplot(no_e_coli, aes(x=N_species_dose, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by N_species_dose - No E. coli")
gg_N_species_dose_no_ecoli


#7
e_coli$temp<-as.factor(e_coli$temp)
gg_temp_ecoli<-
  ggplot(e_coli, aes(x=temp, y=resp_rate)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Temperature")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Temp - E. coli")
gg_temp_ecoli

#8
no_e_coli$temp<-as.factor(no_e_coli$temp)
gg_temp_no_ecoli<-
  ggplot(no_e_coli, aes(x=temp, y=resp_rate, color=col_num)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Temp - No E. coli")
gg_temp_no_ecoli

#9
no_e_coli$sym_state<-as.factor(no_e_coli$sym_state)
gg_sym_state_no_ecoli<-
  ggplot(no_e_coli, aes(x=sym_state, y=resp_rate)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Sym state - No E. coli")
gg_sym_state_no_ecoli

#10
e_coli$sym_state<-as.factor(e_coli$sym_state)
gg_sym_state_ecoli<-
  ggplot(e_coli, aes(x=sym_state, y=resp_rate)) +
  geom_boxplot(width=0.8) +
  geom_jitter(width=0.15, alpha=0.9) +
 # geom_line(aes(group=e_coli_plate), col="darkgray")+
  ylab("Respirometry rate")+
  xlab("Treat ID")+
  theme(legend.position="none", plot.title = element_text(size = 9)) +
  #scale_color_manual(name = "Day of experiment",
                     #labels = c("Day 1","Day 11"),
                   # values = c("royalblue","darkorchid1"))+
 # scale_x_discrete(labels=c("Day 1","Day 11")) +
    theme(axis.text.x = element_text(angle=90, vjust=.5, hjust=1))+ #this makes the x axis labels up and down instead of side to side to prevent overlapping
 annotate("text", x = Inf, y = Inf, label = paste("  "), vjust = 1, hjust = 1, size=3)+
  ggtitle("Resp rate by Sym state - No E. coli")
gg_sym_state_ecoli

```

```{r SUBSETS E COLI for t tests verus the control for that group}
#ammonium high 20C
sym_fed_ammonium_high_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="10" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0"& resp_all.data$e_coli_plate=="0")
apo_fed_ammonium_high_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="10" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
sym_starved_ammonium_high_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="10" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_starved_ammonium_high_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="10" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
#nitrate high 20C
sym_fed_nitrate_high_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="18" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_fed_nitrate_high_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="18" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
sym_starved_nitrate_high_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="18" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_starved_nitrate_high_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="18" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")

#control 20C
sym_fed_control_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="0" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_fed_control_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="0" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
sym_starved_control_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="0" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_starved_control_20C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="0" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")

#ammonium 5uM 20C
sym_fed_ammonium_5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S"& resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_fed_ammonium_5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
sym_starved_ammonium_5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_starved_ammonium_5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
#nitrate 5um 20C
sym_fed_nitrate_5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_fed_nitrate_5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
sym_starved_nitrate_5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_starved_nitrate_5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")

#ammonium high 30C
sym_fed_ammonium_high_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="10" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_fed_ammonium_high_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="10" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
sym_starved_ammonium_high_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="10" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_starved_ammonium_high_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="10" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
#nitrate high 30C
sym_fed_nitrate_high_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="18" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_fed_nitrate_high_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="18" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
sym_starved_nitrate_high_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="18" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_starved_nitrate_high_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="18" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")

#control 30C
sym_fed_control_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="0" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_fed_control_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="0" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
sym_starved_control_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="0" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_starved_control_30C_no_ecoli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="0" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")

#ammonium 5um 30C
sym_fed_ammonium_5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_fed_ammonium_5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
sym_starved_ammonium_5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_starved_ammonium_5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
#nitrate 5um 30C
sym_fed_nitrate_5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" &  resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_fed_nitrate_5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
sym_starved_nitrate_5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_starved_nitrate_5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")

#nitrate 1.5um 30C
sym_fed_nitrate_1.5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_fed_nitrate_1.5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
sym_starved_nitrate_1.5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_starved_nitrate_1.5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")

#nitrate 1.5um 20C
sym_fed_nitrate_1.5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_fed_nitrate_1.5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
sym_starved_nitrate_1.5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_starved_nitrate_1.5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")

#ammonium 7.5um 30C
sym_fed_ammonium_7.5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_fed_ammonium_7.5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
sym_starved_ammonium_7.5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")
apo_starved_ammonium_7.5um_30C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="0")

#ammonium 7.5um 20C
sym_fed_ammonium_7.5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_fed_ammonium_7.5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
sym_starved_ammonium_7.5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
apo_starved_ammonium_7.5um_20C_no_ecoli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="0")
```

```{r SUBSETS NO E COLI for t tests verus the control for that group}
#ammonium high 20C
sym_fed_ammonium_high_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="10" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1"& resp_all.data$e_coli_plate=="1")
apo_fed_ammonium_high_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="10" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
sym_starved_ammonium_high_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="10" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_starved_ammonium_high_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="10" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
#nitrate high 20C
sym_fed_nitrate_high_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="18" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_fed_nitrate_high_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="18" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
sym_starved_nitrate_high_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="18" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_starved_nitrate_high_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="18" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")

#control 20C
sym_fed_control_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="0" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_fed_control_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="0" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
sym_starved_control_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="0" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_starved_control_20C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="0" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")

#ammonium 5uM 20C
sym_fed_ammonium_5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S"& resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_fed_ammonium_5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
sym_starved_ammonium_5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_starved_ammonium_5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
#nitrate 5um 20C
sym_fed_nitrate_5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_fed_nitrate_5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
sym_starved_nitrate_5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_starved_nitrate_5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")

#ammonium high 30C
sym_fed_ammonium_high_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="10" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_fed_ammonium_high_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="10" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
sym_starved_ammonium_high_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="10" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_starved_ammonium_high_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="10" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
#nitrate high 30C
sym_fed_nitrate_high_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="18" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_fed_nitrate_high_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="18" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
sym_starved_nitrate_high_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="18" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_starved_nitrate_high_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="18" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")

#control 30C
sym_fed_control_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="0" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_fed_control_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="0" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
sym_starved_control_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="0" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_starved_control_30C_e_coli <-subset(resp_all.data, resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="0" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")

#ammonium 5um 30C
sym_fed_ammonium_5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_fed_ammonium_5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
sym_starved_ammonium_5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_starved_ammonium_5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
#nitrate 5um 30C
sym_fed_nitrate_5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" &  resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_fed_nitrate_5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
sym_starved_nitrate_5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_starved_nitrate_5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")

#nitrate 1.5um 30C
sym_fed_nitrate_1.5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_fed_nitrate_1.5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
sym_starved_nitrate_1.5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_starved_nitrate_1.5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")

#nitrate 1.5um 20C
sym_fed_nitrate_1.5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_fed_nitrate_1.5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
sym_starved_nitrate_1.5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_starved_nitrate_1.5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="N" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="1.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")

#ammonium 7.5um 30C
sym_fed_ammonium_7.5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_fed_ammonium_7.5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
sym_starved_ammonium_7.5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")
apo_starved_ammonium_7.5um_30C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="30"& resp_all.data$e_coli_plate=="1")

#ammonium 7.5um 20C
sym_fed_ammonium_7.5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="F" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_fed_ammonium_7.5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="F" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
sym_starved_ammonium_7.5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="S" & resp_all.data$food=="S" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
apo_starved_ammonium_7.5um_20C_e_coli <-subset(resp_all.data, resp_all.data$N_species=="A" & resp_all.data$sym_state=="A" & resp_all.data$food=="S" & resp_all.data$N_dose=="7.5" & resp_all.data$temp=="20"& resp_all.data$e_coli_plate=="1")
```

```{r t tests compared to relevant control - E. coli}
#sym fed 20C, all compared to control sym fed 20C
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_nitrate_1.5um_20C_e_coli$resp_rate)
#p=0.1042
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_ammonium_5um_20C_e_coli$resp_rate)
#p=0.4771
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_nitrate_5um_20C_e_coli$resp_rate)
#p=0.5502
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_ammonium_7.5um_20C_e_coli$resp_rate)
#p=0.232
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_ammonium_high_20C_e_coli$resp_rate)
#p=0.2024
t.test(sym_fed_control_20C_e_coli$resp_rate, sym_fed_nitrate_high_20C_e_coli$resp_rate)
#p=0.1682

#sym fed 30C, all compared to control sym fed 30C
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_nitrate_1.5um_30C_e_coli$resp_rate)
#p=0.4524
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_ammonium_5um_30C_e_coli$resp_rate)
#p=0.6342
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_nitrate_5um_30C_e_coli$resp_rate)
#p=0.96
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_ammonium_7.5um_30C_e_coli$resp_rate)
#p=0.0127
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_ammonium_high_30C_e_coli$resp_rate)
#p=0.1383
t.test(sym_fed_control_30C_e_coli$resp_rate, sym_fed_nitrate_high_30C_e_coli$resp_rate)
#p=0.7563

#___ Sym starved 

#sym starved 20C, all compared to control sym fed 20C
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_nitrate_1.5um_20C_e_coli$resp_rate)
#p=0.0556
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_ammonium_5um_20C_e_coli$resp_rate)
#p= 0.1202
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_nitrate_5um_20C_e_coli$resp_rate)
#p= 0.7142
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_ammonium_7.5um_20C_e_coli$resp_rate)
#p= 0.3707
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_ammonium_high_20C_e_coli$resp_rate)
#p= 0.4604
t.test(sym_starved_control_20C_e_coli$resp_rate, sym_starved_nitrate_high_20C_e_coli$resp_rate)
#p= 0.7019

#sym starved 30C, all compared to control sym fed 30C
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_nitrate_1.5um_30C_e_coli$resp_rate)
#p=0.1613
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_ammonium_5um_30C_e_coli$resp_rate)
#p=0.6113
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_nitrate_5um_30C_e_coli$resp_rate)
#p=0.9276
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_ammonium_7.5um_30C_e_coli$resp_rate)
#p= 0.05253
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_ammonium_high_30C_e_coli$resp_rate)
#p= 0.6491
t.test(sym_starved_control_30C_e_coli$resp_rate, sym_starved_nitrate_high_30C_e_coli$resp_rate)
#p= 0.1142

#___ apo fed 

#apo fed 20C
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_nitrate_1.5um_20C_e_coli$resp_rate)
#p= 0.4355
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_ammonium_5um_20C_e_coli$resp_rate)
#p= 0.6995
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_nitrate_5um_20C_e_coli$resp_rate)
#p= 0.9564
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_ammonium_7.5um_20C_e_coli$resp_rate)
#p= 0.6399
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_ammonium_high_20C_e_coli$resp_rate)
#p= 0.4461
t.test(apo_fed_control_20C_e_coli$resp_rate, apo_fed_nitrate_high_20C_e_coli$resp_rate)
#p= 0.3519

#apo fed 30C
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_nitrate_1.5um_30C_e_coli$resp_rate)
#p=0.5267
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_ammonium_5um_30C_e_coli$resp_rate)
#p=0.4213
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_nitrate_5um_30C_e_coli$resp_rate)
#p=0.5673
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_ammonium_7.5um_30C_e_coli$resp_rate)
#p= 0.3054
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_ammonium_high_30C_e_coli$resp_rate)
#p= 0.4159
t.test(apo_fed_control_30C_e_coli$resp_rate, apo_fed_nitrate_high_30C_e_coli$resp_rate)
#p= 0.04549

#___ apo starved

#apo fed 20C
t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_nitrate_1.5um_20C_e_coli$resp_rate)
#p= 0.748
t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_ammonium_5um_20C_e_coli$resp_rate)
#p= 0.9562
t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_nitrate_5um_20C_e_coli$resp_rate)
#p=0.08441
t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_ammonium_7.5um_20C_e_coli$resp_rate)
#p= 0.7132
t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_ammonium_high_20C_e_coli$resp_rate)
#p=0.1955
t.test(apo_starved_control_20C_e_coli$resp_rate, apo_starved_nitrate_high_20C_e_coli$resp_rate)
#p= 0.06472

#apo fed 30C
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_nitrate_1.5um_30C_e_coli$resp_rate)
#p= 0.3879
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_ammonium_5um_30C_e_coli$resp_rate)
#p= 0.714
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_nitrate_5um_30C_e_coli$resp_rate)
#p= 0.2444
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_ammonium_7.5um_30C_e_coli$resp_rate)
#p= 0.9543
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_ammonium_high_30C_e_coli$resp_rate)
#p= 0.2142
t.test(apo_starved_control_30C_e_coli$resp_rate, apo_starved_nitrate_high_30C_e_coli$resp_rate)
#p= 0.1545


```
```{r t tests No e coli}
#TO DO JANUARY 5
#sym fed 20C, all compared to control sym fed 20C
t.test(sym_fed_control_20C_no_e_coli$resp_rate, sym_fed_nitrate_1.5um_20C_no_e_coli$resp_rate)
#p=
t.test(sym_fed_control_20C_no_e_coli$resp_rate, sym_fed_ammonium_5um_20C_no_e_coli$resp_rate)
#p=
t.test(sym_fed_control_20C_no_e_coli$resp_rate, sym_fed_nitrate_5um_20C_no_e_coli$resp_rate)
#p=
t.test(sym_fed_control_20C_no_e_coli$resp_rate, sym_fed_ammonium_7.5um_20C_no_e_coli$resp_rate)
#p=
t.test(sym_fed_control_20C_no_e_coli$resp_rate, sym_fed_ammonium_high_20C_no_e_coli$resp_rate)
#p=
t.test(sym_fed_control_20C_no_e_coli$resp_rate, sym_fed_nitrate_high_20C_no_e_coli$resp_rate)
#p=

#sym fed 30C, all compared to control sym fed 30C
t.test(sym_fed_control_30C_no_e_coli$resp_rate, sym_fed_nitrate_1.5um_30C_no_e_coli$resp_rate)
#p=
t.test(sym_fed_control_30C_no_e_coli$resp_rate, sym_fed_ammonium_5um_30C_no_e_coli$resp_rate)
#p=
t.test(sym_fed_control_30C_no_e_coli$resp_rate, sym_fed_nitrate_5um_30C_no_e_coli$resp_rate)
#p=
t.test(sym_fed_control_30C_no_e_coli$resp_rate, sym_fed_ammonium_7.5um_30C_no_e_coli$resp_rate)
#p=
t.test(sym_fed_control_30C_no_e_coli$resp_rate, sym_fed_ammonium_high_30C_no_e_coli$resp_rate)
#p=
t.test(sym_fed_control_30C_no_e_coli$resp_rate, sym_fed_nitrate_high_30C_no_e_coli$resp_rate)
#p=

#___ Sym starved 

#sym starved 20C, all compared to control sym fed 20C
t.test(sym_starved_control_20C_no_e_coli$resp_rate, sym_starved_nitrate_1.5um_20C_no_e_coli$resp_rate)
#p=
t.test(sym_starved_control_20C_no_e_coli$resp_rate, sym_starved_ammonium_5um_20C_no_e_coli$resp_rate)
#p= 
t.test(sym_starved_control_20C_no_e_coli$resp_rate, sym_starved_nitrate_5um_20C_no_e_coli$resp_rate)
#p= 
t.test(sym_starved_control_20C_no_e_coli$resp_rate, sym_starved_ammonium_7.5um_20C_no_e_coli$resp_rate)
#p= 
t.test(sym_starved_control_20C_no_e_coli$resp_rate, sym_starved_ammonium_high_20C_no_e_coli$resp_rate)
#p= 
t.test(sym_starved_control_20C_no_e_coli$resp_rate, sym_starved_nitrate_high_20C_no_e_coli$resp_rate)
#p= 

#sym starved 30C, all compared to control sym fed 30C
t.test(sym_starved_control_30C_no_e_coli$resp_rate, sym_starved_nitrate_1.5um_30C_no_e_coli$resp_rate)
#p=
t.test(sym_starved_control_30C_no_e_coli$resp_rate, sym_starved_ammonium_5um_30C_no_e_coli$resp_rate)
#p=
t.test(sym_starved_control_30C_no_e_coli$resp_rate, sym_starved_nitrate_5um_30C_no_e_coli$resp_rate)
#p=
t.test(sym_starved_control_30C_no_e_coli$resp_rate, sym_starved_ammonium_7.5um_30C_no_e_coli$resp_rate)
#p= 
t.test(sym_starved_control_30C_no_e_coli$resp_rate, sym_starved_ammonium_high_30C_no_e_coli$resp_rate)
#p= 
t.test(sym_starved_control_30C_no_e_coli$resp_rate, sym_starved_nitrate_high_30C_no_e_coli$resp_rate)
#p=

#___ apo fed 

#apo fed 20C
t.test(apo_fed_control_20C_no_e_coli$resp_rate, apo_fed_nitrate_1.5um_20C_no_e_coli$resp_rate)
#p= 
t.test(apo_fed_control_20C_no_e_coli$resp_rate, apo_fed_ammonium_5um_20C_no_e_coli$resp_rate)
#p= 
t.test(apo_fed_control_20C_no_e_coli$resp_rate, apo_fed_nitrate_5um_20C_no_e_coli$resp_rate)
#p= 
t.test(apo_fed_control_20C_no_e_coli$resp_rate, apo_fed_ammonium_7.5um_20C_no_e_coli$resp_rate)
#p= 
t.test(apo_fed_control_20C_no_e_coli$resp_rate, apo_fed_ammonium_high_20C_no_e_coli$resp_rate)
#p= 
t.test(apo_fed_control_20C_no_e_coli$resp_rate, apo_fed_nitrate_high_20C_no_e_coli$resp_rate)
#p= 

#apo fed 30C
t.test(apo_fed_control_30C_no_e_coli$resp_rate, apo_fed_nitrate_1.5um_30C_no_e_coli$resp_rate)
#p=
t.test(apo_fed_control_30C_no_e_coli$resp_rate, apo_fed_ammonium_5um_30C_no_e_coli$resp_rate)
#p=
t.test(apo_fed_control_30C_no_e_coli$resp_rate, apo_fed_nitrate_5um_30C_no_e_coli$resp_rate)
#p=
t.test(apo_fed_control_30C_no_e_coli$resp_rate, apo_fed_ammonium_7.5um_30C_no_e_coli$resp_rate)
#p= 
t.test(apo_fed_control_30C_no_e_coli$resp_rate, apo_fed_ammonium_high_30C_no_e_coli$resp_rate)
#p= 
t.test(apo_fed_control_30C_no_e_coli$resp_rate, apo_fed_nitrate_high_30C_no_e_coli$resp_rate)
#p= 

#___ apo starved

#apo fed 20C
t.test(apo_starved_control_20C_no_e_coli$resp_rate, apo_starved_nitrate_1.5um_20C_no_e_coli$resp_rate)
#p= 
t.test(apo_starved_control_20C_no_e_coli$resp_rate, apo_starved_ammonium_5um_20C_no_e_coli$resp_rate)
#p=
t.test(apo_starved_control_20C_no_e_coli$resp_rate, apo_starved_nitrate_5um_20C_no_e_coli$resp_rate)
#p=
t.test(apo_starved_control_20C_no_e_coli$resp_rate, apo_starved_ammonium_7.5um_20C_no_e_coli$resp_rate)
#p= 
t.test(apo_starved_control_20C_no_e_coli$resp_rate, apo_starved_ammonium_high_20C_no_e_coli$resp_rate)
#p=
t.test(apo_starved_control_20C_no_e_coli$resp_rate, apo_starved_nitrate_high_20C_no_e_coli$resp_rate)
#p= 

#apo fed 30C
t.test(apo_starved_control_30C_no_e_coli$resp_rate, apo_starved_nitrate_1.5um_30C_no_e_coli$resp_rate)
#p= 
t.test(apo_starved_control_30C_no_e_coli$resp_rate, apo_starved_ammonium_5um_30C_no_e_coli$resp_rate)
#p= 
t.test(apo_starved_control_30C_no_e_coli$resp_rate, apo_starved_nitrate_5um_30C_no_e_coli$resp_rate)
#p= 
t.test(apo_starved_control_30C_no_e_coli$resp_rate, apo_starved_ammonium_7.5um_30C_no_e_coli$resp_rate)
#p= 
t.test(apo_starved_control_30C_no_e_coli$resp_rate, apo_starved_ammonium_high_30C_no_e_coli$resp_rate)
#p= 
t.test(apo_starved_control_30C_no_e_coli$resp_rate, apo_starved_nitrate_high_30C_no_e_coli$resp_rate)
#p=
```

